const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),multer=require('multer'),{v4:uuidv4}=require('uuid'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const app=express();app.use(cors());app.use(express.json());app.use(express.static(__dirname));app.use('/uploads',express.static(path.join(__dirname,'uploads')));
if(!fs.existsSync('uploads'))fs.mkdirSync('uploads');const upload=multer({dest:'uploads/'});
const SUPER={email:"laserianbilly@gmail.com",password:"ayuk237$",momo:"677054956"};const JWT_SECRET=process.env.JWT_SECRET||"NEXA_SECRET_2026";
let db={shops:{},posts:[],chats:{},transactions:[],owners:{}};if(fs.existsSync('db.json')){try{db=JSON.parse(fs.readFileSync('db.json'))}catch(e){}}function save(){fs.writeFileSync('db.json',JSON.stringify(db,null,2))}
if(!Object.keys(db.shops).length){const h=bcrypt.hashSync("shop123",10);db.owners['shop@homereach.com']={id:uuidv4(),shopId:'homereach',email:'shop@homereach.com',password:h,name:'HomeReach'};db.shops['homereach']={id:'homereach',name:'HomeReach Phone Repair',city:'Tiko',country:'CM',flag:'🇨🇲',currency:'XAF',privatePayment:'677054956',paymentMethod:'MTN MoMo',accountName:'AYUK BILLY',sales:0,commission:0,ownerEmail:'shop@homereach.com',emoji:'📱'};db.posts=[{id:uuidv4(),shopId:'homereach',shopName:'HomeReach Phone Repair',city:'Tiko',country:'CM',flag:'🇨🇲',currency:'XAF',caption:'🔥 iPhone Screen Repair - Worldwide! #Tiko',price:15000,mediaUrl:'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',mediaType:'image',likes:0,comments:[],time:new Date().toISOString()}];save()}
function auth(req,res,next){const t=req.headers.authorization?.split(' ')[1];if(!t)return res.status(401).json({error:'No token'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid'})}}
app.post('/api/shop/register',async(req,res)=>{const{shopId,name,email,password,city,country,privatePayment,accountName}=req.body;if(db.owners[email])return res.json({success:false,error:'Email used'});const h=await bcrypt.hash(password,10);const oid=uuidv4();const cid=shopId.toLowerCase().replace(/[^a-z0-9-]/g,'');db.owners[email]={id:oid,shopId:cid,email,password:h,name};db.shops[cid]={id:cid,name:name+"'s Shop",city:city||'Tiko',country:country||'CM',flag:'🌍',currency:'USD',privatePayment,accountName:accountName||name,paymentMethod:'MTN MoMo',sales:0,commission:0,ownerEmail:email,emoji:'📦'};save();const token=jwt.sign({ownerId:oid,shopId:cid,email},JWT_SECRET);res.json({success:true,token,shop:db.shops[cid]})});
app.post('/api/shop/login',async(req,res)=>{const{email,password}=req.body;const o=db.owners[email];if(!o)return res.json({success:false,error:'Not found'});const ok=await bcrypt.compare(password,o.password);if(!ok)return res.json({success:false,error:'Wrong pass'});const token=jwt.sign({ownerId:o.id,shopId:o.shopId,email},JWT_SECRET);res.json({success:true,token,shop:db.shops[o.shopId]})});
app.get('/api/shop/me',auth,(req,res)=>{const s=db.shops[req.user.shopId];res.json({shop:s,posts:db.posts.filter(p=>p.shopId===req.user.shopId),chats:db.chats[req.user.shopId]||[],transactions:db.transactions.filter(t=>t.shopId===req.user.shopId)})});
app.get('/api/posts',(req,res)=>{let p=db.posts.sort((a,b)=>new Date(b.time)-new Date(a.time));if(req.query.country&&req.query.country!=='WORLD')p=p.filter(x=>x.country===req.query.country);res.json(p)});
app.post('/api/posts/create',upload.single('media'),(req,res)=>{const{shopId,caption,price,currency,country}=req.body;const shop=db.shops[shopId];let url=req.body.mediaUrl||'';let type='text';if(req.file){url='/uploads/'+req.file.filename;type=req.file.mimetype?.startsWith('video')?'video':'image'}const post={id:uuidv4(),shopId,shopName:shop.name,city:shop.city,country:country||shop.country,flag:shop.flag,currency:currency||shop.currency,caption,price:Number(price),mediaType:type,mediaUrl:url,likes:0,comments:[],time:new Date().toISOString()};db.posts.unshift(post);save();res.json({success:true,post})});
app.post('/api/posts/like/:id',(req,res)=>{const p=db.posts.find(x=>x.id===req.params.id);if(p){p.likes++;save()}res.json({success:true})});
app.get('/api/chats/:shopId',(req,res)=>res.json(db.chats[req.params.shopId]||[]));
app.post('/api/chats/send',(req,res)=>{const{shopId,sender,message}=req.body;if(!db.chats[shopId])db.chats[shopId]=[];db.chats[shopId].push({id:uuidv4(),shopId,sender,message,time:new Date().toISOString(),timeDisplay:new Date().toLocaleTimeString()});save();res.json({success:true})});
app.get('/api/shops',(req,res)=>res.json(Object.values(db.shops)));
app.get('/api/countries',(req,res)=>res.json([{code:'CM',name:'Cameroon',flag:'🇨🇲'},{code:'NG',name:'Nigeria',flag:'🇳🇬'},{code:'US',name:'USA',flag:'🇺🇸'},{code:'GB',name:'UK',flag:'🇬🇧'},{code:'FR',name:'France',flag:'🇫🇷'},{code:'AE',name:'Dubai',flag:'🇦🇪'},{code:'WORLD',name:'Worldwide',flag:'🌍'}]));
app.post('/api/pay/private',(req,res)=>{const{shopId,customerPhone,amount}=req.body;const shop=db.shops[shopId];let c=customerPhone||'237000000000';c=c.toString().replace(/\s/g,'');if(c.startsWith('6'))c='237'+c;const tx={id:uuidv4(),shopId,shopName:shop.name,flag:shop.flag,customerPhone:c,shopPrivate:shop.privatePayment,accountName:shop.accountName,amount:Number(amount),currency:shop.currency,shopReceives:Math.floor(Number(amount)*0.9),commission:Math.floor(Number(amount)*0.1),commissionTo:SUPER.momo,status:'PENDING',time:new Date().toISOString()};db.transactions.unshift(tx);shop.sales+=Number(amount);shop.commission+=tx.commission;save();res.json({success:true,transaction:tx})});
app.get('/api/transactions',(req,res)=>res.json(db.transactions));
app.post('/api/super/login',(req,res)=>{if(req.body.email===SUPER.email&&req.body.password===SUPER.password)return res.json({success:true,token:'SUPER'});res.json({success:false})});
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log(`🌍 NEXA V7 LIVE on ${PORT} - Super MoMo ${SUPER.momo}`));
